
services:

  backend:
    build: ./backend
    container_name: ecom_backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: mongodb://development:testpassword@db:27017/Ecommerce
    depends_on:
      - db

  db:
    image: mongo:5.0.3
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - ecvl:/data/db

  # Tuỳ chọn: mở lại nếu cần web quản lý MongoDB
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo_ui
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: development
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
  #     ME_CONFIG_MONGODB_URL: mongodb://development:testpassword@db:27017/

volumes:
  ecvl:
